### ISSUE TITLE
Install dependenecies in `install.py`

### ISSUE THREAD

**Issue by ljleb** [s1dlx/sd-webui-bayesian-merger#10]
Webui extensions can put a file `install.py` at the root of the repo. The webui host will execute this file before starting up. It is possible to install dependencies in this file. See the docs for more info: https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Developing-extensions

For convenience, I suggest to install dependencies listed under `requirements.txt` using `install.py`.

**Comment by s1dlx** [comment]
Good suggestion, I’ll add requirements there.
