### ISSUE TITLE
Allow for classic interpolation options on-top of merge block weights

### ISSUE THREAD

**Issue by saftle** [s1dlx/sd-webui-bayesian-merger#14]
One advantage of https://github.com/hako-mikan/sd-webui-supermerger is that it allows you to subtract the base SD 1.5 (or any model for that matter) prior to doing the block weight merge. This makes merges much more efficient than regular block weight merges, since you are not saturating with more of base SD and instead only merging in new trained data.

Would this be possible to impement here as well?

**Comment by s1dlx** [comment]
@saftle yep sounds very doable. I need to check into supermerger codebase, how that does work in practice?

subtract sd1.5 from both models and then merge? Then I imagine you need to “add” back sd1.5

or is it simply a + (b -sd1.5) kind of merge?

**Comment by saftle** [comment]
Yep, simply  `a + (b - sd1.5)` or even `a + (b - a)`. And then the block merge comes after (or before, not sure). It leads to a much better merge than straight up block weights.

**Comment by s1dlx** [comment]
I can even do `a * (1-w) + w*(b-a)` _during_ the block merge. That prevents from loading yet another model (model_c/sd1.5)

unless there's a value in experimenting with different `model_c`
