### ISSUE TITLE
webui batch size

### ISSUE THREAD

**Issue by s1dlx** [s1dlx/sd-webui-bayesian-merger#24]
add `webui-batch-size` to cli options. This will return multiple images for each api call, they need to be squashed in a single list in case of `batch-size` > 1

**Comment by ljleb** [comment]
For now, explicitly using `--webui-batch-size` seems to be a good solution. I just wanted to mention this to make sure we take into consideration the general case.

I think it would be more appropriate to be able to specify the default value for any api property. Maybe something like using a default paylod `default.yaml` that can be used by all payloads as fallback values. If there is a clean way to forward any api property using `--webui-<kebab-case-property-name>` cli args, then maybe that could work too.

**Comment by s1dlx** [comment]
closed by #26 where hydra configs are implemented
