### ISSUE TITLE
Hopefully Simple Feature - Best results dumped to log

### ISSUE THREAD

**Issue by LoFiApostasy** [s1dlx/sd-webui-bayesian-merger#31]
Such an awesome job, this git makes me so happy.  Thanks!

Reviewing the output log I can see the various weights but finding the "Best" weight seems to be impossible to discern.
The best results is dumped into the console, but I dont see it captured anywhere else.
Can we get the console output also saved to the log?

Example log output:
`...last entry out of 100
{"target": 5.368659411867459, "params": {"base_alpha": 0.8377178379395807, "block_0": 0.5912576037075312, "block_1": 0.219540892877366, "block_10": 0.9733859306484954, "block_11": 0.9972918968460628, "block_12": 0.1436796715716302, "block_13": 0.8046326284786746, "block_14": 0.9446532495523224, "block_15": 0.5495523349269184, "block_16": 0.20377728591955635, "block_17": 0.34752946464540435, "block_18": 0.04344746485226936, "block_19": 0.30353029807894516, "block_2": 0.3515946770111045, "block_20": 0.5949518834682795, "block_21": 0.7699234728162386, "block_22": 0.4285295289847719, "block_23": 0.9649783995693728, "block_24": 0.4807781097467194, "block_3": 0.972969174089362, "block_4": 0.45268990437249024, "block_5": 0.8855778015663418, "block_6": 0.8647170789035926, "block_7": 0.42552862442014583, "block_8": 0.2260575429865025, "block_9": 0.4501523607414235}, "datetime": {"datetime": "2023-03-23 16:20:50", "elapsed": 31804.978845, "delta": 315.889125}}`

Example console output:
```
Best run:
best base_alpha:
0.38907805521574623

best weights:
0.6645853080842493,0.2509265405053803,0.30323389450354854,0.17549752593956036,0.6797806829752624,0.16708197708174466,0.8213573724012218,0.8933529041088031,0.31918223008733493,0.4709609821114096,0.8468646416270249,0.23688971959120386,0.9819297096323844,0.5302339993515092,0.7116941338566791,0.7292665022390346,0.6997645581077122,0.26762754921484944,0.8736926655949656,0.8809942704105306,0.20757106414291016,0.23379109148693622,0.19133144586009754,0.8387402972021962,0.7222066304431761
Saving best merge: E:\Projects\automatic1111\models\Stable-diffusion\bbwm-mix1-mix2-32bit.ckpt
loading: E:\Projects\automatic1111\models\Stable-diffusion\mix1.ckpt
loading: E:\Projects\automatic1111\models\Stable-diffusion\mix2.ckpt
merging 1/2: 100%|████████████████████████████████████████████████████████████████| 1133/1133 [00:02<00:00, 532.15it/s]
merging 2/2: 100%|████████████████████████████████████████████████████████████| 1145/1145 [00:00<00:00, 1071025.44it/s]
Saving E:\Projects\automatic1111\models\Stable-diffusion\bbwm-mix1-mix2-best-32bit.ckpt
```

**Comment by s1dlx** [comment]
@LoFiApostasy done in #26 !
