### ISSUE TITLE
[Question] Does skip_position_ids refer to a clip skip being applied to the model merge or to image inferencing?

### ISSUE THREAD

**Issue by mariaWitch** [s1dlx/sd-webui-bayesian-merger#43]
Question is as titled. I'm a little confused on the skip_position_ids. Does this refer to "Clip Skip" as meant in the WebUI settings, where it is applied to image inferencing, or does it refer to something else entirely involving the merging of the models?

**Comment by ljleb** [comment]
See this message https://github.com/s1dlx/sd-webui-bayesian-merger/pull/28#issuecomment-1481836439 for an answer. Note that the value is 0-based instead of 1-based like it is in the webui.
